apiVersion: apps/v1
kind: Deployment
metadata:
  name: catan
  labels:
    app: catan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catan
  template:
    metadata:
      labels:
        app: catan
    spec:
      containers:
      - name: catan
        image: localhost:32000/catan
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: catan-service
spec:
  selector:
    app: catan
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catan-ingress
spec:
  rules:
  - host: catan.forno96.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catan-service
            port:
              number: 4567
